apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-assist-config
  namespace: openshift-pipelines
  labels:
    assist.tekton.dev/release: "devel"
    app.kubernetes.io/component: tekton-assist
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-assist
data:
  PROVIDER: "gemini"
  OPENAI_MODEL: "gemini-2.5-flash"
  OPENAI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta/openai/"
  OPENAI_TEMPERATURE: "0.2"
  OPENAI_MAX_TOKENS: "400"
  OPENAI_TIMEOUT: "30s"
  DEBUG: "false"
