apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-pipelines
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml

images:
- name: ghcr.io/openshift-pipelines/tekton-assist/assist
  newName: ghcr.io/openshift-pipelines/tekton-assist/assist
  newTag: devel
