apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-assist-config
  namespace: {{ default .Release.Namespace (index .Values "tekton-assist" "namespace") }}
  labels:
    {{- include "tekton-assist.labels" . | nindent 4 }}
data:
  PROVIDER: {{ index .Values "tekton-assist" "openai" "provider" | quote }}
  OPENAI_MODEL: {{ index .Values "tekton-assist" "openai" "model" | quote }}
  OPENAI_BASE_URL: {{ index .Values "tekton-assist" "openai" "baseURL" | quote }}
  OPENAI_TEMPERATURE: {{ index .Values "tekton-assist" "openai" "temperature" | quote }}
  OPENAI_MAX_TOKENS: {{ index .Values "tekton-assist" "openai" "maxTokens" | quote }}
  OPENAI_TIMEOUT: {{ index .Values "tekton-assist" "openai" "timeout" | quote }}
  DEBUG: {{ index .Values "tekton-assist" "openai" "debug" | quote }}
