{{- if index .Values "tekton-assist" "openai" "apiKey" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-assist-openai-api-key
  labels:
    {{- include "tekton-assist.labels" . | nindent 4 }}
data:
  openai-api-key: {{ index .Values "tekton-assist" "openai" "apiKey" | b64enc | quote}}
{{- end }}
